### ISSUE TITLE
Doesn't always work. 

### ISSUE THREAD

**Issue by dkonhplay** [Firippu/Project64-Crack#1]
Doesn't always work.

**Comment by BlumpkinKing87** [comment]
Doesn't work at all for me...

**Comment by Firippu** [comment]
Place "Project64_patched.exe" within the installation directory along side of "Project64.exe". Now run the patched executable. If the registration dialog doesn't automatically appear, then click on the tab Help->SupportProject64. On this dialog you'll see a blue clickable link, this opens another dialog to enter in a unique registration code. Enter any text into the box & click OK. If you're using the patched executable, it will accept the code. You can now exit & continue to use the original unpatched executable. Optionally, you can delete the patched executable, as it is no longer needed. Now when you click the tab Help->SupportProject64, that once blue clickable link is now grey & disabled, meaning it is registered. The support dialog with timer will no longer appear. Also, make sure you're using the same program version as detailed within the GitHub project description. If registration issues still occur, please provide a demonstration and any other useful information. Thanks.

**Comment by BlumpkinKing87** [comment]
> Place "Project64_patched.exe" within the installation directory along side of "Project64.exe". Now run the patched executable. If the registration dialog doesn't automatically appear, then click on the tab Help->SupportProject64. On this dialog you'll see a blue clickable link, this opens another dialog to enter in a unique registration code. Enter any text into the box & click OK. If you're using the patched executable, it will accept the code. You can now exit & continue to use the original unpatched executable. Optionally, you can delete the patched executable, as it is no longer needed. Now when you click the tab Help->SupportProject64, that once blue clickable link is now grey & disabled, meaning it is registered. The support dialog with timer will no longer appear. Also, make sure you're using the same program version as detailed within the GitHub project description. If registration issues still occur, please provide a demonstration and any other useful information. Thanks.

Worked perfectly, thank you!

**Comment by kevintanner800** [comment]
Mine would not work until I let the patched exe through tinywall (firewall) and access the internet. works great thanks!

**Comment by Firippu** [comment]
Issues are resolved. Thanks for the feedback. I will make the instructions more understandable.
